// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPBP0u18O1mdsnDenTRWfpBCAIUWHtVE',
    appId: '1:180173520635:web:364e945eb920faa3403a5e',
    messagingSenderId: '180173520635',
    projectId: 'studentwellnessapp-43cd1',
    authDomain: 'studentwellnessapp-43cd1.firebaseapp.com',
    storageBucket: 'studentwellnessapp-43cd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2NuFTeM7J-Jz71g9gmbX2aGKllYf2l0',
    appId: '1:180173520635:android:dfe292c041011c2f403a5e',
    messagingSenderId: '180173520635',
    projectId: 'studentwellnessapp-43cd1',
    storageBucket: 'studentwellnessapp-43cd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy042ogq_sFa1NeuNfAD90k76PIDMTHCU',
    appId: '1:180173520635:ios:3d15fc10f28126a9403a5e',
    messagingSenderId: '180173520635',
    projectId: 'studentwellnessapp-43cd1',
    storageBucket: 'studentwellnessapp-43cd1.firebasestorage.app',
    iosBundleId: 'com.example.studentWellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy042ogq_sFa1NeuNfAD90k76PIDMTHCU',
    appId: '1:180173520635:ios:3d15fc10f28126a9403a5e',
    messagingSenderId: '180173520635',
    projectId: 'studentwellnessapp-43cd1',
    storageBucket: 'studentwellnessapp-43cd1.firebasestorage.app',
    iosBundleId: 'com.example.studentWellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkPBP0u18O1mdsnDenTRWfpBCAIUWHtVE',
    appId: '1:180173520635:web:cdc4d6be477917b6403a5e',
    messagingSenderId: '180173520635',
    projectId: 'studentwellnessapp-43cd1',
    authDomain: 'studentwellnessapp-43cd1.firebaseapp.com',
    storageBucket: 'studentwellnessapp-43cd1.firebasestorage.app',
  );
}
